- name: "install JAVA jdk 11"
  apt:
   name: default-jdk
   update_cache: no


- name: "add jdk to Envirenment Variables"
  lineinfile:
   path: /etc/environment
   line:  'JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64/"' 
   state: present
   backup: yes