version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: devops
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: always

  spring-backend:
    image: mahmoudtimoumi/${DOCKER_TAG_BACKEND}
    container_name: spring-backend
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    restart: always

  angular-frontend:
    image: mahmoudtimoumi/${DOCKER_TAG_FRONTEND}
    container_name: angular-frontend
    ports:
      - "80:80"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
